# Generated by Django 3.2.10 on 2021-12-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("no_inf", models.PositiveIntegerField(default=1)),
                ("inf_name", models.CharField(max_length=50)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("nairobi", "Nairobi"),
                            ("mombasa", "Mombasa"),
                            ("kisumu", "Kisumu"),
                            ("eldoret", "Eldoret"),
                            ("makindu", "Makindu"),
                            ("marsabit", "Marsabit"),
                            ("kisii", "Kisii"),
                            ("nyamira", "Nyamira"),
                            ("migori", "Migori"),
                            ("muhanga", "Muhanga"),
                            ("nyeri", "Nyeri"),
                            ("kiambu", "Kiambu"),
                            ("nyandarua", "Nyandarua"),
                            ("machakos", "Machakos"),
                            ("makueni", "Makueni"),
                        ],
                        default="nairobi",
                        max_length=50,
                    ),
                ),
                ("estate", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
