# Generated by Django 3.2.9 on 2021-12-06 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mime',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mime',
            name='location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('mime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mime.mime')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
