# Generated by Django 3.2.9 on 2021-12-06 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mime', '0002_auto_20211206_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='mime',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mime',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mime',
            name='name',
        ),
        migrations.AddField(
            model_name='mime',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mime.location'),
        ),
    ]
