# Generated by Django 3.2.9 on 2021-12-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mime', '0003_auto_20211206_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='estate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
