# Generated by Django 3.2.9 on 2021-12-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mime', '0005_auto_20211206_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mime',
            name='no_dumps',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
